export enum EnvVariable {
  SupportedChainId = "SupportedChainId",
  ETH_HOSTNAME_HTTP = "ETH_HOSTNAME_HTTP",
  ETH_HOSTNAME_WS = "ETH_HOSTNAME_WS",
  FEATURE_FLAG_TBTC_V2 = "FEATURE_FLAG_TBTC_V2",
  FEATURE_FLAG_MULTI_APP_STAKING = "FEATURE_FLAG_MULTI_APP_STAKING",
  FEATURE_FLAG_POSTHOG = "FEATURE_FLAG_POSTHOG",
  POSTHOG_HOSTNAME_HTTP = "POSTHOG_HOSTNAME_HTTP",
  POSTHOG_API_KEY = "POSTHOH_API_KEY",
  THRESHOLD_MOCK_TBTC = "THRESHOLD_MOCK_TBTC",
}
