export enum ExternalHref {
  thresholdGithub = "https://github.com/threshold-network/token-dashboard",
  thresholdDiscord = "https://discord.gg/WXK9PC6SRF",
  metamaskHomePage = "https://metamask.io/",
  stakingContractLeanMore = "https://github.com/threshold-network/solidity-contracts/issues/53",
  preNodeSetup = "https://docs.nucypher.com/en/latest/pre_application/running_a_node.html",
  preStakingProvidersList = "https://docs.nucypher.com/en/latest/pre_application/node_providers.html",
  exchangeRateLearnMore = "https://blog.threshold.network/threshold-launch/",
  keepDapp = "https://dashboard.keep.network/",
  keepDappAuthPage = "https://dashboard.keep.network/applications/threshold",
  nuDapp = "https://stake.nucypher.network/manage",
  stakingBonusDocs = "https://forum.threshold.network/t/interim-era-incentive-schemes-1-one-off-migration-stake-bonus-2-ongoing-stable-yield/297",
  stakedUs = "https://staked.us/",
  bisonTrails = "https://bisontrails.co/",
  blackDaemon = "https://blockdaemon.com/",
  boar = "https://boar.network/",
  figment = "https://www.figment.io/",
  lowFeeValidation = "https://lowfeevalidation.com/",
  ankr = "https://www.ankr.com/",
  p2pValidator = "https://p2p.org/",
  infStones = "https://infstones.com/",
  setupNodes = "https://docs.threshold.network/",
}
