export enum ModalType {
  SelectWallet = "SELECT_WALLET",
  UpgradeToT = "UPGRADE_TO_T",
  UpgradedToT = "UPGRADED_TO_T",
  TransactionIsPending = "TRANSACTION_IS_PENDING",
  TransactionIsWaitingForConfirmation = "TRANSACTION_IS_WAITING_FOR_CONFIRMATION",
  TransactionFailed = "TRANSACTION_FAILED",
  StakingChecklist = "STAKING_CHECKLIST",
  ConfirmStakingParams = "CONFIRM_STAKING_PARAMS",
  StakeSuccess = "STAKE_SUCCESS",
  UnstakeT = "UNSTAKE_T",
  UnstakeSuccess = "UNSTAKE_SUCCESS",
  StakeSuccessPreNeeded = "STAKE_SUCCESS_PRE_NEEDED",
  SubmitPreAddress = "SUBMIT_PRE_ADDRESS",
}
