name: Deploy to a GCP Bucket
description: "Builds and deploys to a Google Cloud Storage Bucket"
inputs:
  # Currently the action only supports `environment` = `goerli`.
  environment:
    description: >
      The environment on which the action should be used. For example `goerli`.
      Will be used to deterine environment variables and decide which legacy
      packages should be used for building.
    required: true
  ethUrlHttp:
    description: The HTTP ETH API URL.
    required: true
  ethUrlWS:
    description: The WebSocket ETH API URL.
    required: true
  useUpstreamBuilds:
    description: True if the upstream builds should be used.
    required: true
    default: "false"
  upstreamBuilds:
    description: Upstream builds (required if `useUpstreamBuilds==true`).
    required: false
  dependentPackagesTag:
    description: >
      Tag which should be used to pull latest non-legacy `threshold-network` and
      `keep-network` packages with contracts (required if
      `useUpstreamBuilds==false`). For example `dapp-dev-goerli`.
    required: false
  gcpServiceKey:
    description: JSON key for Google Cloud Platform service account.
    required: true
  gcpBucketName:
    description: The name of the bucket where code wil be deployed.
    required: true
  preview:
    description: True if the code should be pushed to the preview bucket.
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: "yarn"

    # We need this step because the `@keep-network/tbtc` which we update in
    # next step has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
    # downloads one of its sub-dependencies via unathenticated `git://`
    # protocol. That protocol is no longer supported. Thanks to this step
    # `https://` is used instead of `git://`.
    - name: Configure git to don't use unauthenticated protocol
      shell: bash
      run: git config --global url."https://".insteadOf git://

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Get upstream packages versions
      if: inputs.upstreamBuilds == 'true'
      uses: keep-network/ci/actions/upstream-builds-query@v2
      id: upstream-builds-query
      with:
        upstream-builds: ${{ inputs.upstreamBuilds }}
        query: |
          threshold-contracts-version = github.com/threshold-network/solidity-contracts#version

    - name: Set packages versions
      shell: bash
      id: set-packages-versions
      run: |
        if [ ${{ inputs.useUpstreamBuilds }} = 'false' ]; then
          echo "::set-output name=threshold-contracts-version::${{ inputs.dependentPackagesTag }}"
        else
          echo "::set-output name=threshold-contracts-version::${{ steps.upstream-builds-query.outputs.threshold-contracts-version }}"
        fi

    # Currently we only support `environment` = `goerli`. We provide explicit
    # version of the `keep-core` package, because using `goerli` tag results in
    # `expected manifest` error - probably caused by bug in Yarn:
    # https://github.com/yarnpkg/yarn/issues/4731.

    # TODO: Add upgrade of @keep-network/random-beacon, @keep-network/ecdsa,
    # @keep-network/tbtc-v2 once they'll be added as dashboard's dependencies.
    - name: Resolve contracts
      shell: bash
      run: |
        yarn upgrade \
          @threshold-network/solidity-contracts@${{ steps.set-packages-versions.outputs.threshold-contracts-version }} \
          @keep-network/keep-core@1.8.1-goerli.0 \
          @keep-network/keep-ecdsa@${{ inputs.environment }} \
          @keep-network/tbtc@${{ inputs.environment }} \
          @keep-network/coverage-pools@${{ inputs.environment }}

    - name: Run postinstall script
      shell: bash
      # `yarn upgrade` doesn't trigger the `postinstall` script.
      run: yarn run postinstall

    - name: Load environment variables
      uses: keep-network/ci/actions/load-env-variables@v2
      with:
        environment: ${{ inputs.environment }}

    - name: Build
      shell: bash
      run: yarn build
      env:
        # `head_ref` variable property is only available when the event that
        # triggers a workflow run is either pull_request or pull_request_target.
        # For `workflow_dispatch` and `push`, the `PUBLIC_URL` will resolve to `/`.`
        PUBLIC_URL: /${{ github.head_ref }}
        CHAIN_ID: ${{ env.NETWORK_ID }}
        ETH_HOSTNAME_HTTP: ${{ inputs.ethUrlHttp }}
        ETH_HOSTNAME_WS: ${{ inputs.ethUrlWS }}

    # We need this step to set correct value of `bucket-path` in the
    # `cp-storage-bucket-action`. We can't use `${{ github.head_ref }}` directly
    # there, because then when `head_ref` is empty, the parameter `bucket-path`
    # is not forwarded to the runner and empty value is assigned to the
    # `bucket-path` input instead of the default value (`.`). This results in
    # incorrect passing of docker arguments and setting wrong bucket address.
    - name: Configure `bucket-path`
      shell: bash
      id: set-bucket-path
      run: |
        if [ ${{ github.head_ref }} == '' ]; then
          echo "::set-output name=bucket-path::."
        else
          echo "::set-output name=bucket-path::${{ github.head_ref }}"
        fi

    - name: Deploy to GCP
      uses: thesis/gcp-storage-bucket-action@v3.1.0
      with:
        service-key: ${{ inputs.gcpServiceKey }}
        project: ${{ env.GOOGLE_PROJECT_ID }}
        bucket-name: ${{ inputs.gcpBucketName }}
        bucket-path: ${{ steps.set-bucket-path.outputs.bucket-path }}
        build-folder: build
        set-website: ${{ inputs.preview == 'false' }}
        home-page-path: index.html
        error-page-path: index.html

    - name: Post preview URL to PR
      if: inputs.preview == 'true'
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Preview uploaded to https://${{ inputs.gcpBucketName }}/${{ github.head_ref }}/index.html.'
          })
